// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { Editora } from '../editora';
import {Livro}  from '../livro';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {

  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];
  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;

  constructor(servEditora: ControleEditoraService, servLivros: ControleLivrosService) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }

  // Método ngOnInit modificado para usar Promise e then
  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros()
      .then(livros => {
        this.livros = livros;  // Atribui os livros após a Promise ser resolvida
      })
      .catch(erro => {
        console.error("Erro ao obter livros", erro);
      });
  }

  // Método excluir modificado para aceitar código como String
  excluir = (codigo: string): void => {
    console.log("Excluir livro com código:", codigo)
    this.servLivros.excluir(codigo)
      .then(() => {
        // Atualiza a lista de livros somente após a exclusão
        return this.servLivros.obterLivros();
      })
      .then(livros => {
        this.livros = livros;  // Atualiza os livros após a exclusão
      })
      .catch(erro => {
        console.error("Erro ao excluir livro", erro);
      });
  };

  obterNome = (codEditora: number): string | undefined => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}
<main>
  <h1 class='text-center'>Catálogo de Livros</h1>
  <div class='container'>

  <table class='table table-striped'>
    <thead class='text-bg-dark table-dark'>
      <tr>
      <th>Título</th>
      <th>Resumo</th>
      <th>Editora</th>
      <th>Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td class="titulo">
          <p>{{livro.titulo}}</p>
          <button *ngIf="livro.codigo" class="btn btn-danger" (click)="excluir(livro.codigo)">
            Excluir
          </button>
        </td>
        <td class="resumo">{{livro.resumo}}</td>
        <td class="editora">{{obterNome(livro.codEditora)}}</td>
        <td class="autores">
          <ul>
            <li *ngFor="let autor of livro.autores">
              {{autor}}
            </li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
  </div>
</main>

// clientes/livros-react/src/LivroLista.js
import React, { useState, useEffect } from 'react';
import ControleEditora, { editoras } from './controle/ControleEditora';
import ControleLivros from './controle/ControleLivros';

const controleLivro = new ControleLivros();
const controleEditora = new ControleEditora(editoras);

// Definição do componente auxiliar LinhaLivro
const LinhaLivro = (props) => {
    const { livro, excluir } = props;

    // Obtendo o nome da editora a partir de ControleEditora
    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

    return (
        <tr>
            <td>
                <div>{livro.titulo}</div>
                <button className="btn btn-danger btn-sm" onClick={() => excluir(livro._id)}>
                    Excluir
                </button>
            </td>
            <td>{livro.resumo}</td>
            <td>{nomeEditora}</td>
            <td>
                <ul className="list-unstyled">
                    {livro.autores.map((autor, index) => (
                        <li key={index}>{autor}</li>
                    ))}
                </ul>
            </td>
        </tr>
    );
};

// Definição do componente LivroLista
const LivroLista = () => {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);

    // Atualização para carregar os livros de forma assíncrona via API
    useEffect(() => {
        if (!carregado) {
            controleLivro.obterLivros()
                .then((dados) => {
                    setLivros(dados); // Atualiza o estado com os dados recebidos
                    setCarregado(true);
                })
                .catch((erro) => {
                    console.error("Erro ao carregar livros:", erro);
                });
        }
    }, [carregado]);

    // Método excluir atualizado para lidar com exclusão via API
    const excluir = (id) => {
        controleLivro.excluir(id)
            .then((sucesso) => {
                if (sucesso) {
                    setLivros((livros) => livros.filter((livro) => livro._id !== id));
                }
            })
            .catch((erro) => {
                console.error("Erro ao excluir livro:", erro);
            });
    };

    // Retorno do componente
    return (
        <main className="container my-4">
            <h1 className="mb-4">Catálogo de Livros</h1>
            <table className="table table-striped table-bordered table-hover">
                <thead className="table-dark">
                    <tr>
                        <th className="col-2">Título</th>
                        <th className="col-6">Resumo</th>
                        <th className="col-2">Editora</th>
                        <th className="col-2">Autores</th>
                    </tr>
                </thead>
                <tbody>
                    {/* Geração das linhas de livros com base nos dados da API */}
                    {livros.map((livro) => (
                        <LinhaLivro
                            key={livro._id} // Usando _id como chave
                            livro={livro}
                            excluir={excluir}
                        />
                    ))}
                </tbody>
            </table>
        </main>
    );
};

export default LivroLista;
